---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nest-flux-kind
  namespace: flux-system
spec:
  chart:
    spec:
      chart: nest-flux-kind
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nest-flux-kind
      version: '>=1.0.0'
  interval: 5m0s
